### ISSUE TITLE
Functional tests, and list/tuple to rrset_records

### ISSUE THREAD

**Issue by lingfish** [StackStorm-Exchange/stackstorm-powerdns#13]
Hi, I'm wondering if your move to Actions isn't running [run_all_actions.yaml](https://github.com/StackStorm-Exchange/stackstorm-powerdns/blob/master/actions/run_all_actions.yaml) anymore in tests?

I ask because I'm trying to get list/dict/tuple to `rrset_records`, using `create_records` working, and I cannot.  So I thought I'd check your tests, and noticed you only specify an IP, omitting the "disabled" field?

Kind of a two-in-one issue from me, sorry.

**Comment by lingfish** [comment]
So confused... even when running `powerdns.create_records` manually from SS UI, I cannot get it to accept `rrset_records`.

* If I give it a quoted string, I get `Key 'content' not present or not a String`
* If I supply either a tuple or list ( () or [] ), I get `'['203.56.123.100']': Parsing record content` errors
* A simple YAML list, like in your run_all_actions, same or similar error

FWIW, I'm running:

```pip  $ /opt/stackstorm/virtualenvs/powerdns/bin/pip list
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.9
idna               3.3
pip                20.3.3
python-powerdns    2.1.0
requests           2.26.0
setuptools         51.3.3
six                1.16.0
urllib3            1.26.7
wheel              0.36.2
```

When supplying a simple IP (in the UI), I get this:

```json
{
  "stdout": "",
  "stderr": "raising error code 422
",
  "exit_code": 0,
  "result": "code=422 http://some.host:8081/api/v1/servers/localhost/zones/some.fqdn.: Key 'content' not present or not a String"
}
```

Params as per UI:

```"parameters": {
    "log_level": "DEBUG",
    "rrset_changetype": "REPLACE",
    "rrset_comments": [
      "From NetBox"
    ],
    "rrset_name": "some.fqdn.",
    "rrset_rtype": "A",
    "rrset_records": [
      "1.1.1.1"
    ],
    "zone_name": "some.fqdn.",
    "rrset_ttl": 86400,
    "server_id": "localhost",
    "timeout": 15,
    "response_timeout": 5,
    "debug": false
  }
```

Running pdns-server 4.6.0~alpha1+master.164.g06f6fac9b-1pdns.buster

**Comment by nzlosh** [comment]
`powerdns.create_records` works as expected on my dev machine.  It was run against powerdns 4.1.
```
action.ref: powerdns.create_records
context.user: st2admin
parameters: 
  rrset_changetype: REPLACE
  rrset_name: www.functionaltest.local.
  rrset_records:
  - 127.0.0.4
  - 127.0.0.10
  rrset_rtype: A
  rrset_ttl: 3600.0
  zone_name: functionaltest.local.
status: succeeded (2s elapsed)
start_timestamp: Sun, 19 Dec 2021 23:08:19 UTC
end_timestamp: Sun, 19 Dec 2021 23:08:21 UTC
log: 
  - status: requested
    timestamp: '2021-12-19T23:08:19.900000Z'
  - status: scheduled
    timestamp: '2021-12-19T23:08:20.292000Z'
  - status: running
    timestamp: '2021-12-19T23:08:20.580000Z'
  - status: succeeded
    timestamp: '2021-12-19T23:08:21.811000Z'
result: 
  exit_code: 0
  result: ''
  stderr: ''
  stdout: ''
```
If the python-powerdns modules is reporting the same sort of errors, then I'd be more inclined to think there may be API changes in 4.6 that the python module doesn't handle.

**Comment by nzlosh** [comment]
For the sake of completeness, here is a call using the `disabled` option.
```
id: 61c06620c4da20d0bbf50d3c
action.ref: powerdns.create_records
context.user: st2admin
parameters: 
  rrset_changetype: REPLACE
  rrset_name: www.functionaltest.local.
  rrset_records:
  - 127.0.0.4
  - 127.0.0.10
  - - 127.0.0.11
    - false
  rrset_rtype: A
  rrset_ttl: 3600.0
  zone_name: functionaltest.local.
status: succeeded (1s elapsed)
start_timestamp: Mon, 20 Dec 2021 11:16:48 UTC
end_timestamp: Mon, 20 Dec 2021 11:16:49 UTC
log: 
  - status: requested
    timestamp: '2021-12-20T11:16:48.108000Z'
  - status: scheduled
    timestamp: '2021-12-20T11:16:48.525000Z'
  - status: running
    timestamp: '2021-12-20T11:16:49.120000Z'
  - status: succeeded
    timestamp: '2021-12-20T11:16:49.914000Z'
result: 
  exit_code: 0
  result: ''
  stderr: ''
  stdout: ''
```

**Comment by lingfish** [comment]
Interesting.  I've just spun up a test pdns, Version: 4.1.6-3+deb10u1, then pointed my existing SS server at it... same result/errors!

```yaml
parameters:
  debug: false
  log_level: DEBUG
  response_timeout: 5
  rrset_changetype: REPLACE
  rrset_comments:
  - From NetBox
  rrset_name: host.test.domain.
  rrset_records:
  - 1.1.1.1
  rrset_rtype: A
  rrset_ttl: 86400
  server_id: localhost
  timeout: 15
  zone_name: test.domain.
```

```json
{
  "stdout": "",
  "stderr": "raising error code 422",
  "exit_code": 0,
  "result": "code=422 http://server:8081/api/v1/servers/localhost/zones/test.domain.: Key 'content' not present or not a String"
}
```

So, this is down to the `python-powerdns` code, or something else buried deep in StackStorm?!  What version(s) of each are you on?

**Comment by nzlosh** [comment]
The virtualenv has the following version:

```
certifi==2021.10.8
charset-normalizer==2.0.9
idna==3.3
python-powerdns @ git+https://github.com/outini/python-powerdns.git@8caa8e283dca8609e91dcc67785366bb412d527f
PyYAML==6.0
requests==2.26.0
six==1.16.0
urllib3==1.26.7
```
I'll try force the version to use the pypi version

**Comment by nzlosh** [comment]
How did you install the pack?  The `requirements.txt` points to the github verison of the python module `git+https://github.com/outini/python-powerdns.git#egg=python-powerdns`, it's quite strange that the pypi version was pulled in.

**Comment by nzlosh** [comment]
Even after forcing the pypi version `python-powerdns==2.1.0` the create records functions correctly.
```
id: 61c19380c4da20d0bbf50e66
action.ref: powerdns.create_records
context.user: st2admin
parameters: 
  rrset_changetype: REPLACE
  rrset_name: www.functionaltest.local.
  rrset_records:
  - 127.0.0.4
  - 127.0.0.10
  - - 127.0.0.11
    - false
  rrset_rtype: A
  rrset_ttl: 3600.0
  zone_name: functionaltest.local.
status: succeeded (2s elapsed)
start_timestamp: Tue, 21 Dec 2021 08:42:40 UTC
end_timestamp: Tue, 21 Dec 2021 08:42:42 UTC
log: 
  - status: requested
    timestamp: '2021-12-21T08:42:40.629000Z'
  - status: scheduled
    timestamp: '2021-12-21T08:42:41.031000Z'
  - status: running
    timestamp: '2021-12-21T08:42:41.270000Z'
  - status: succeeded
    timestamp: '2021-12-21T08:42:42.085000Z'
result: 
  exit_code: 0
  result: ''
  stderr: ''
  stdout: ''
```
